# Generated by Django 4.1.1 on 2022-09-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_leave',
            old_name='staff',
            new_name='staff_id',
        ),
    ]
