# Generated by Django 4.1.1 on 2022-09-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_staff_staff_leave_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_notification',
            old_name='staff',
            new_name='staff_id',
        ),
    ]
