# Generated by Django 4.1.1 on 2022-09-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_attendance_attendance_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='course_id',
        ),
    ]
